# Generated by Django 5.2.8 on 2025-11-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Placement date', null=True)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'Morning'), ('MD', 'Midday'), ('PM', 'Evening')], help_text='Shift time (AM/MD/PM)', max_length=10, null=True)),
                ('physician_name', models.CharField(blank=True, help_text="Physician's full name", max_length=255, null=True)),
                ('physician_id', models.IntegerField(blank=True, help_text='Physician unique ID', null=True)),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=255, null=True)),
                ('specialty', models.CharField(blank=True, db_index=True, help_text='Medical specialty', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', help_text='Placement status', max_length=50, null=True)),
                ('area', models.CharField(blank=True, help_text='Hospital area/wing', max_length=255, null=True)),
                ('room_number', models.CharField(blank=True, help_text='Room number', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
                'ordering': ['-date', 'shift'],
                'indexes': [models.Index(fields=['-date', 'shift'], name='placements__date_f90e8d_idx'), models.Index(fields=['department'], name='placements__departm_8c300c_idx'), models.Index(fields=['specialty'], name='placements__special_cb8dfe_idx'), models.Index(fields=['status'], name='placements__status_050fcb_idx')],
            },
        ),
    ]
