# Generated by Django 5.2.8 on 2025-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='shift',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('MD', 'Midday'), ('PM', 'Evening'), ('CLOSED', 'Closed')], help_text='Shift time (AM/MD/PM/CLOSED)', max_length=10, null=True),
        ),
    ]
